version: '3.8'

services:
  nginx:
    container_name: nginx
    image: "nginx:stable-alpine"
    ports:
      - "8002:80"
    volumes:
      - ./configs/nginx.conf/:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    networks:
      # - backend
      - ws_sv_rmq

  #контейнеры backend'a
  php:
    container_name: php
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    networks:
      - ws_sv_rmq
      - test

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10-management-alpine
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    networks:
      - backend
      - test

  supervisor:
    build:
      context: dockerfiles
      dockerfile: supervisor.Dockerfile
    container_name: supervisor
    volumes:
      - ./src:/var/www/laravel
      - ./configs/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./configs/supervisord.conf:/etc/supervisord.conf:ro
      - ./src/storage/logs:/etc/supervisor/logs
    command: "supervisord -n -c /etc/supervisord.conf"
    ports:
      - 6001:6001
    networks:
      - backend
      # - ws_sv_rmq

  #вспомогательные контейнеры
  composer:
    container_name: composer
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    networks:
      - ws_sv_rmq

  artisan:
    container_name: artisan
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: [ "php", "/var/www/laravel/artisan" ]
    networks:
      - ws_sv_rmq

networks:
  backend:
    driver: bridge
    external: true
  ws_sv_rmq:
    driver: bridge
  test:
    driver: bridge